package com.github.kklisura.cdt.protocol.types.input;

/*-
 * #%L
 * cdt-java-client
 * %%
 * Copyright (C) 2018 - 2026 Kenan Klisura
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import com.github.kklisura.cdt.protocol.support.annotations.Experimental;
import com.github.kklisura.cdt.protocol.support.annotations.Optional;
import com.github.kklisura.cdt.protocol.support.annotations.ParamName;
import java.util.List;

/** Parameters for the dispatchKeyEvent command. */
public class DispatchKeyEventParameters {

  @ParamName("type")
  private DispatchKeyEventType type;

  @Optional
  @ParamName("modifiers")
  private Integer modifiers;

  @Optional
  @ParamName("timestamp")
  private Double timestamp;

  @Optional
  @ParamName("text")
  private String text;

  @Optional
  @ParamName("unmodifiedText")
  private String unmodifiedText;

  @Optional
  @ParamName("keyIdentifier")
  private String keyIdentifier;

  @Optional
  @ParamName("code")
  private String code;

  @Optional
  @ParamName("key")
  private String key;

  @Optional
  @ParamName("windowsVirtualKeyCode")
  private Integer windowsVirtualKeyCode;

  @Optional
  @ParamName("nativeVirtualKeyCode")
  private Integer nativeVirtualKeyCode;

  @Optional
  @ParamName("autoRepeat")
  private Boolean autoRepeat;

  @Optional
  @ParamName("isKeypad")
  private Boolean isKeypad;

  @Optional
  @ParamName("isSystemKey")
  private Boolean isSystemKey;

  @Optional
  @ParamName("location")
  private Integer location;

  @Experimental
  @Optional
  @ParamName("commands")
  private List<String> commands;

  /** Type of the key event. */
  public DispatchKeyEventType getType() {
    return type;
  }

  /** Type of the key event. */
  public DispatchKeyEventParameters setType(DispatchKeyEventType type) {
    this.type = type;
    return this;
  }

  /**
   * Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default:
   * 0).
   */
  public Integer getModifiers() {
    return modifiers;
  }

  /**
   * Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default:
   * 0).
   */
  public DispatchKeyEventParameters setModifiers(Integer modifiers) {
    this.modifiers = modifiers;
    return this;
  }

  /** Time at which the event occurred. */
  public Double getTimestamp() {
    return timestamp;
  }

  /** Time at which the event occurred. */
  public DispatchKeyEventParameters setTimestamp(Double timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Text as generated by processing a virtual key code with a keyboard layout. Not needed for for
   * `keyUp` and `rawKeyDown` events (default: "")
   */
  public String getText() {
    return text;
  }

  /**
   * Text as generated by processing a virtual key code with a keyboard layout. Not needed for for
   * `keyUp` and `rawKeyDown` events (default: "")
   */
  public DispatchKeyEventParameters setText(String text) {
    this.text = text;
    return this;
  }

  /**
   * Text that would have been generated by the keyboard if no modifiers were pressed (except for
   * shift). Useful for shortcut (accelerator) key handling (default: "").
   */
  public String getUnmodifiedText() {
    return unmodifiedText;
  }

  /**
   * Text that would have been generated by the keyboard if no modifiers were pressed (except for
   * shift). Useful for shortcut (accelerator) key handling (default: "").
   */
  public DispatchKeyEventParameters setUnmodifiedText(String unmodifiedText) {
    this.unmodifiedText = unmodifiedText;
    return this;
  }

  /** Unique key identifier (e.g., 'U+0041') (default: ""). */
  public String getKeyIdentifier() {
    return keyIdentifier;
  }

  /** Unique key identifier (e.g., 'U+0041') (default: ""). */
  public DispatchKeyEventParameters setKeyIdentifier(String keyIdentifier) {
    this.keyIdentifier = keyIdentifier;
    return this;
  }

  /** Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: ""). */
  public String getCode() {
    return code;
  }

  /** Unique DOM defined string value for each physical key (e.g., 'KeyA') (default: ""). */
  public DispatchKeyEventParameters setCode(String code) {
    this.code = code;
    return this;
  }

  /**
   * Unique DOM defined string value describing the meaning of the key in the context of active
   * modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
   */
  public String getKey() {
    return key;
  }

  /**
   * Unique DOM defined string value describing the meaning of the key in the context of active
   * modifiers, keyboard layout, etc (e.g., 'AltGr') (default: "").
   */
  public DispatchKeyEventParameters setKey(String key) {
    this.key = key;
    return this;
  }

  /** Windows virtual key code (default: 0). */
  public Integer getWindowsVirtualKeyCode() {
    return windowsVirtualKeyCode;
  }

  /** Windows virtual key code (default: 0). */
  public DispatchKeyEventParameters setWindowsVirtualKeyCode(Integer windowsVirtualKeyCode) {
    this.windowsVirtualKeyCode = windowsVirtualKeyCode;
    return this;
  }

  /** Native virtual key code (default: 0). */
  public Integer getNativeVirtualKeyCode() {
    return nativeVirtualKeyCode;
  }

  /** Native virtual key code (default: 0). */
  public DispatchKeyEventParameters setNativeVirtualKeyCode(Integer nativeVirtualKeyCode) {
    this.nativeVirtualKeyCode = nativeVirtualKeyCode;
    return this;
  }

  /** Whether the event was generated from auto repeat (default: false). */
  public Boolean getAutoRepeat() {
    return autoRepeat;
  }

  /** Whether the event was generated from auto repeat (default: false). */
  public DispatchKeyEventParameters setAutoRepeat(Boolean autoRepeat) {
    this.autoRepeat = autoRepeat;
    return this;
  }

  /** Whether the event was generated from the keypad (default: false). */
  public Boolean getIsKeypad() {
    return isKeypad;
  }

  /** Whether the event was generated from the keypad (default: false). */
  public DispatchKeyEventParameters setIsKeypad(Boolean isKeypad) {
    this.isKeypad = isKeypad;
    return this;
  }

  /** Whether the event was a system key event (default: false). */
  public Boolean getIsSystemKey() {
    return isSystemKey;
  }

  /** Whether the event was a system key event (default: false). */
  public DispatchKeyEventParameters setIsSystemKey(Boolean isSystemKey) {
    this.isSystemKey = isSystemKey;
    return this;
  }

  /**
   * Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
   * 0).
   */
  public Integer getLocation() {
    return location;
  }

  /**
   * Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right (default:
   * 0).
   */
  public DispatchKeyEventParameters setLocation(Integer location) {
    this.location = location;
    return this;
  }

  /**
   * Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are
   * related to but not equal the command names used in `document.execCommand` and
   * NSStandardKeyBindingResponding. See
   * https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h
   * for valid command names.
   */
  public List<String> getCommands() {
    return commands;
  }

  /**
   * Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are
   * related to but not equal the command names used in `document.execCommand` and
   * NSStandardKeyBindingResponding. See
   * https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h
   * for valid command names.
   */
  public DispatchKeyEventParameters setCommands(List<String> commands) {
    this.commands = commands;
    return this;
  }
}
